def build_serverconfig(server):
    return {
        "server_tcp_listener_port": int(server.get("tcp_port", 9700)),
        "server_udp_listener_port": int(server.get("udp_port", 9700)),
        "server_tcp_internal_port": int(server.get("tcp_port", 9700)),
        "server_udp_internal_port": int(server.get("udp_port", 9700)),
        "server_http_port": int(server.get("http_port", 8080)),
        "server_name": server.get("name", "EVO Server"),
        "launch_path": server.get("launch_path", ""),
        "netcode_update_interval": int(server.get("netcode_update_interval", 55)),
        "driver_password": server.get("driver_password", ""),
        "spectator_password": server.get("spectator_password", ""),
        "max_players": int(server.get("max_players", 8)),
        "allowed_cars_list_full": server.get("cars", []),
        "type": server.get("type", "MultiplayerServerListSessionType_RANKED"),
        "cycle": bool(server.get("cycle", True)),
        "admin_password": server.get("admin_password", ""),
        "pi_min": float(server.get("pi_min", 0) or 0),
        "pi_max": float(server.get("pi_max", 0) or 0),
        "property_1": server.get("property_1", []),
        "property_2": server.get("property_2", []),
        "property_3": server.get("property_3", []),
        "entry_list_server_url": server.get("entry_list_server_url", ""),
        "results_post_url": server.get("results_post_url", ""),
        "token": server.get("token", ""),
        "entry_list_path": server.get("entry_list_path", ""),
        "results_path": server.get("results_path", ""),
        "tuning_type": server.get("tuning_type", "TuningAllowed")
    }


def _time_of_day(server, prefix):
    return {
        "year": int(server.get("year", 2024)),
        "month": int(server.get("month", 8)),
        "day": int(server.get("day", 15)),
        "hour": int(server.get(f"{prefix}_hour", server.get("practice_hour", 16))),
        "minute": int(server.get(f"{prefix}_minute", server.get("practice_minute", 0))),
        "second": int(server.get("second", 0)),
        "time_multiplier": int(server.get(f"{prefix}_time_multiplier", server.get("time_multiplier", 1)))
    }


def build_seasondefinition(server):
    game_type = server.get("game_type", "GameModeType_PRACTICE")

    game_config = {
        "practice_duration": int(server.get("practice_length", 300)),
        "practice_time_of_day": _time_of_day(server, "practice"),
        "practice_overtime_waiting_next_session": int(server.get("practice_overtime", server.get("overtime", 10))),
        "practice_max_wait_to_box": int(server.get("practice_max_wait_to_box", server.get("max_wait_to_box", 10)))
    }

    # Race Weekend must contain all four session blocks.
    # This structure matches the command generated by the official Kunos launcher.
    if game_type == "GameModeType_RACE_WEEKEND":
        game_config.update({
            "qualify_duration": int(server.get("qualify_length", 300)),
            "qualify_time_of_day": _time_of_day(server, "qualify"),
            "qualify_overtime_waiting_next_session": int(server.get("qualify_overtime", 10)),
            "qualify_max_wait_to_box": int(server.get("qualify_max_wait_to_box", 10)),

            "warmup_duration": int(server.get("warmup_length", 300)),
            "warmup_time_of_day": _time_of_day(server, "warmup"),
            "warmup_overtime_waiting_next_session": int(server.get("warmup_overtime", 10)),
            "warmup_max_wait_to_box": int(server.get("warmup_max_wait_to_box", 10)),

            "race_duration": int(server.get("race_length", 300)),
            "race_duration_type": server.get("race_duration_type", "GameModeSelectionDuration_TIME"),
            "race_time_of_day": _time_of_day(server, "race"),
            "race_overtime_waiting_next_session": int(server.get("race_overtime", 10)),
            "race_max_wait_to_box": int(server.get("race_max_wait_to_box", 10)),
            "min_waiting_for_players": int(server.get("min_waiting_for_players", 10)),
            "max_waiting_for_players": int(server.get("max_waiting_for_players", 30))
        })

    return {
        "game_type": game_type,
        "event": {
            "track": server.get("track", "Imola"),
            "layout": server.get("layout", "GP"),
            "event_name": server.get("event_name", "GP Time Attack"),
            "track_length": str(server.get("track_length", "4909"))
        },
        "export_json": bool(server.get("export_json", False)),
        "game_config": game_config,
        "weather_type": server.get("weather", "GameModeSelectionWeatherType_CLEAR"),
        "weather_behaviour": server.get("weather_behavior", "GameModeSelectionWeatherBehaviour_STATIC"),
        "initial_grip": server.get("initial_grip", "InitialGrip_GREEN")
    }
